title: Service Robotics Blog
description: This blog will host the latest news regarding the development of the subjects practices
remote_theme: carlosperate/jekyll-theme-rtd

# Theme settings:
site_author: Diego García Currás
repo_url: "https://github.com/dgarcu/service_robotics_blog"
edit_on_github: true
github_docs_folder: true
logo: 'https://raw.githubusercontent.com/dgarcu/service_robotics_blog/master/assets/img/logo.png'
site_favicon: 'https://raw.githubusercontent.com/dgarcu/service_robotics_blog/master/assets/img/favicon.ico'
sticky_navigation: true
prev_next_buttons_location: bottom
search_enabled: true
hljs_style: github-gist
